export type ValidSkills =
  | "Javascript"
  | "HTML"
  | "CSS"
  | "Markdown"
  | "Arduino"
  | "Gazebo"
  | "Fusion360"
  | "Solidworks"
  | "Electronics"
  | "Linux"
  | "Tinkercad"
  | "C/C++"
  | "Bootstrap"
  | "Reverse engineering"
  | "cryptography"
  | "pentesting"
  | "Python"
  | "Docker"
  | "Kubernetes"
  | "PostgreSQL"
  | "canva"
  | "Git"
  | "CI/CD"
  | "IDA Pro"
  | "ROS2"
  | "ReadMe"
  | "MKDocs"
  | "Mintlify"
  | "Postman"
  | "Assembly"
  | "Google Cloud"
  | "Figma"
  | "Supabase"
  | "Vercel"
  | "Netlify"
  | "TensorFlow"
  | "PyTorch"
  | "Laravel"
  | "Flutter"
  | "Django"
  | "FastAPI"
  | "SQL"
  | "SQL injection"
  | "Web exploitation";

export type ValidCategory =
  | "AI/ML"
  | "Robotics"
  | "Electronics"  
  | "3D Modeling"
  | "Technical Writing"
  | "API documentation"
  | "Article writing"
  | "Web Dev"
  | "Mobile Dev"
  | "Cybersecurity"
  | "Penetration Testing"
  | "Cryptography"
  | "Reverse engineering";

export type ValidExpType = "Robotics" | "Cybersecurity" | "Technical Writing";

export type ValidPages =
  | "home"
  | "skills"
  | "projects"
  | "experience"
  | "contact"
  | "contributions"
  | "resume";
